name: release
on:
  push:
    branches: [ master, main ]
jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - run: sudo apt update && sudo apt install -y gnupg
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install Bundler
        run: gem install bundler -v 2.4.22
      - name: Delete `.rustup` directory
        run: rm -rf /home/runner/.rustup # to save disk space
        if: runner.os == 'Linux'
      - name: Delete `.cargo` directory # to save disk space
        run: rm -rf /home/runner/.cargo
        if: runner.os == 'Linux'
      - run: sbt scalafmtCheck test
      - name: Test distribution
        run: |
          python -m pip install requests pexpect
          sbt joerncli/stage querydb/createDistribution
          python -u ./testDistro.py
      - name: Create version tag
        run: |
          # Get current version from build file or generate one based on commit
          TIMESTAMP=$(date +%m%d-%H%M%S)
          VERSION="v${TIMESTAMP}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${VERSION}
          git push origin ${VERSION}
      - name: Build distribution
        run: sbt stage createDistribution
      - name: Trigger release-github workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/release-github.yml/dispatches \
            -d '{"ref":"${{ env.VERSION }}"}'
